// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joplxjwjfudxmpuvadda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcGx4andqZnVkeG1wdXZhZGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjA0ODksImV4cCI6MjA2NTUzNjQ4OX0.pkgAejWTH-isyfW6uIlspCcGvycTiB7jbUOWyNbFz1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);